spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/webstudy?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

jwt:
  tokeneCpiration: 86400
  tokenSignKey: zyh10201314
  tokenHead: token

mybatis:
  mapper-locations:  classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


aliyun:
  accessKeyId: LTAI5tBpZPq9Xzx24eKcREid
  accessKeySecret: FAFZG32ZqsZFcqEpl56BCWzHZKzj06
  oss:
    endPoint: oss-cn-beijing.aliyuncs.com
    bucketName: webstudy
  msm:
    regionId: cn-beijing
    signName: web技术交流学习平台
    templateCode: SMS_205886514
  video:
    regionId: cn-shanghai